name: 'Yarn, Typescript & NPM'
description: 'Build, Lint and Test a typescript package'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        registry-url: https://registry.npmjs.org
        cache: "yarn"

    - run: yarn install --frozen-lockfile --check-files
      shell: 'bash'
    - run: npm run build --if-present
      shell: 'bash'
    - run: npm run lint --if-present
      shell: 'bash'
    - run: git diff --exit-code
      shell: 'bash'
    - run: npm run test --if-present
      shell: 'bash'

