name: "Typescript - Build and Test"

on:
  workflow_call:
    inputs:
      package-manager:
        description: 'Package manager to use "yarn" or "npm"'
        required: false
        type: string
        default: "npm"
      registry-url: 
        description: 'Which registry to publish too NPM or github'
        required:  false
        type: string
        default: "https://npm.pkg.github.com"
      node-version: 
        description: 'Which version of NodeJS to use'
        required:  false
        type: string
        default: "20.x"

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build & Test"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${{ inputs.node-version }}"
          registry-url: "${{ inputs.registry-url }}"
          cache: "${{ inputs.package-manager }}"

      - name: "Install"
        shell: "bash"
        run: |
          if [ "${{ inputs.package-manager }}" == "yarn" ]; then
            yarn install --frozen-lockfile --check-files
          elif [ "${{ inputs.package-manager }}" == "npm" ]; then
            npm install --ci
          else 
            echo "Unknown package-manager ${{ inputs.package-manager }}"
            exit 1
          fi

      - run: npm run build --if-present
      - run: npm run lint --if-present -- --fix=false # ensure eslint is not configured to --fix
      - run: npm run test --if-present


